version: '3'
services:
  mysql:
    build: 
      context: ./database
      args:
        - MYSQL_DATABASE=tfm
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  indices:
    build: .
    depends_on:
      - mysql
    device_requests:
      - driver: nvidia
        capabilities: [gpu]
        count: 2  