version: '3.7'
services:
  mysql:
    build:
      context: ./mysql_database
      args:
        - MYSQL_DATABASE=tfm
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  
  indices:
    build: .
    depends_on:
      - mysql
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    ports:
      - "8501:8501"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
